services:
  control-connector:
    container_name: control-connector
    image: "louisross/spiking-model-control-connector:1.1"
    ports:
      - 5000:5000
  persist-connector:
    container_name: persist-connector
    image: "louisross/spiking-model-persist-connector:1.0"
    ports:
      - 5001:5001
  client:
    container_name: client
    build: ./spiking-model-control
    image: "louisross/spiking-model-control:1.0"
    ports:
      - 3000:3000
    depends_on:
      - control-connector
      - persist-connector
