#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=spiking-model-control \
-v "$(pwd)":/app \
-v "$(pwd)"/../spiking-model-configuration/configuration/:/app/src/configfiles \
-p 8081:3000 \
louisross/spiking-model-control:1.0 \
bash
