services:
  backend:
    container_name: backend
    build: ./backend
    image: "louisross/spiking-model-control-backend:1.0"
    ports:
      - 5000:5000
  client:
    container_name: client
    build: ./client
    image: "louisross/spiking-model-control-client:1.0"
    ports:
      - 3000:3000
    depends_on:
      - backend
